export type UiVariant =
  | 'default'
  | 'primary'
  | 'secondary'
  | 'accent'
  | 'accent-soft'
  | 'muted'
  | 'destructive'
  | 'destructive-soft'
  | 'success'
  | 'success-soft'
  | 'warning'
  | 'warning-soft'
  | 'outline'
  | 'ghost'
  | 'link'
